#!/bin/bash

#SBATCH --qos=bsc_cs
#SBATCH --job-name=cpic.P1
#SBATCH --output=out/P1
#SBATCH --error=err/P1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=48
#SBATCH --exclusive
#SBATCH --time=00:10:00

#ASSUME IS NOT NEEDED workdir=/home/bsc15/bsc15557/cpic/perf/constant-cpus
. ../../modules

ulimit -s 8192

#export NANOS6_REPORT_PREFIX="#"

srun --cpu-bind=verbose,cores ../../cpic base.conf
#srun --cpu-bind=verbose,cores ../../cpic conf/P1
